### PR TITLE
Improve CI Resource Usage

### PR DESCRIPTION
**Pull request by blink1073**
Follows what was done to address https://github.com/pypa/setuptools/issues/3093

### CODE REVIEW

**Comment by pradyunsg** [comment]
> Concurrenty

Thanks for filing this PR! Could you please fix this typo in the commit message: `concurrency`?

**Comment by blink1073** [comment]
> Thanks for filing this PR! Could you please fix this typo in the commit message: concurrency?

Haha thanks, fixed

**Comment by takluyver** [comment]
Thanks! I see this is part of what @di suggested in his email to pypa-committers. While we're here, should we also disable builds on pushes to branches other than `main`, i.e.:

```yaml
on:
  push:
    branches:
      - main
  pull_request:
```

(When I make a PR myself, I'll probably push the branch to this repo, because there's a redirect from takluyver/flit to pypa/flit so long as I don't fork it)

**Comment by blink1073** [comment]
Sounds good, will follow up when I get back to keyboaard

**Pull request merged**
